### ISSUE TITLE
mini bug: incorrect import

### ISSUE THREAD

**Issue by sbalnojan** [Fundamentals-of-Data-Observability/oreilly-fodo-source-code#1]
I think in https://github.com/Fundamentals-of-Data-Observability/oreilly-fodo-source-code/blob/main/ch4/s2-transformation/r2-dbt-agent/dbt-ast/kensu_reporting.py#L84 "kensu_report_rules" needs to be removed, seems like a legacy piece of code.

**Comment by sbalnojan** [comment]
@andypetrella

**Comment by andypetrella** [comment]
Ooopsy, many thanks @sbalnojan !!!
Fixed in https://github.com/Fundamentals-of-Data-Observability/oreilly-fodo-source-code/commit/13be299a8034e0d085baf9375b20bc2267233892
